server:
  port: 8001
spring:
  application:
    name: gateway
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${MCLUSTER_IP}:${MCLUSTER_PORT}/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
zuul:
  sensitive-headers: Access-Control-Allow-Origin,Access-Control-Allow-Methods